const wordsWithHints = [
    { word: "algorithm", hint: "A step-by-step procedure for solving a problem." },
    { word: "python", hint: "A popular programming language." },
    { word: "astronaut", hint: "Someone who travels to space." },
    { word: "microscope", hint: "Used to see tiny objects." },
    { word: "volcano", hint: "A mountain that erupts." },
    { word: "ecosystem", hint: "A community of living organisms." },
    { word: "bicycle", hint: "A vehicle with two wheels." },
    { word: "tornado", hint: "A destructive vortex of wind." },
    { word: "giraffe", hint: "An animal with a long neck." },
    { word: "compass", hint: "Used to find directions." },
    { word: "rainforest", hint: "A dense, tropical forest." },
    { word: "hamburger", hint: "A popular fast food." },
    { word: "diamond", hint: "A valuable gemstone." },
    { word: "kangaroo", hint: "A marsupial from Australia." },
    { word: "chocolate", hint: "A sweet treat made from cocoa." },
    { word: "rainbow", hint: "Appears after rain and sunshine." },
    { word: "penguin", hint: "A bird that cannot fly but swims." },
    { word: "island", hint: "Land surrounded by water." },
    { word: "oxygen", hint: "A gas essential for life." },
    { word: "calendar", hint: "Used to keep track of dates." },
    { word: "library", hint: "A place with many books." },
    { word: "cactus", hint: "A plant that grows in deserts." },
    { word: "electricity", hint: "Powers lights and machines." },
    { word: "telescope", hint: "Used to see distant objects." },
    { word: "butterfly", hint: "An insect with colorful wings." },
    { word: "laptop", hint: "A portable computer." },
    { word: "elephant", hint: "The largest land animal." },
    { word: "volleyball", hint: "A sport played with a net and ball." },
    { word: "keyboard", hint: "Used to type on a computer." },
    { word: "hurricane", hint: "A severe tropical storm." },
    { word: "mountain", hint: "A large, natural elevation of the earth." },
    { word: "oasis", hint: "A fertile area in a desert." },
    { word: "seahorse", hint: "A small marine animal shaped like a horse." },
    { word: "zebra", hint: "A striped animal from Africa." },
    { word: "fireworks", hint: "Explosive displays in the sky." },
    { word: "sandcastle", hint: "Built on beaches with sand." },
    { word: "pyramid", hint: "A triangular ancient structure in Egypt." },
    { word: "satellite", hint: "Orbits planets or stars." },
    { word: "marathon", hint: "A long-distance running race." },
    { word: "compass", hint: "Used to find directions." },
    { word: "glacier", hint: "A large, slow-moving mass of ice." },
    { word: "jigsaw", hint: "A type of puzzle with pieces to fit together." },
    { word: "spaceship", hint: "A vehicle used for space travel." },
    { word: "coconut", hint: "A fruit from tropical palm trees." },
    { word: "fossil", hint: "Preserved remains of ancient life." },
    { word: "carnival", hint: "A festival with rides and games." },
    { word: "banana", hint: "A yellow tropical fruit." },
    { word: "trophy", hint: "A prize for winning." },
    { word: "planet", hint: "Orbits a star, like Earth." }
  ];
  



   const kidsWordList = [
    { word: "apple", hint: "A red or green fruit often found in pies." },
    { word: "banana", hint: "A long yellow fruit loved by monkeys." },
    { word: "grape", hint: "A small, round fruit used to make wine." },
    { word: "orange", hint: "A citrus fruit that shares its name with a color." },
    { word: "peach", hint: "A fuzzy fruit with a pit inside." },
    { word: "mango", hint: "A tropical fruit with sweet, juicy flesh." },
    { word: "cherry", hint: "A small red fruit often used as a topping." },
    { word: "lemon", hint: "A sour yellow fruit used in lemonade." },
    { word: "kiwi", hint: "A small, brown fruit with green flesh inside." },
    { word: "melon", hint: "A large fruit that includes watermelon and cantaloupe." },
    { word: "tiger", hint: "A large orange cat with black stripes." },
    { word: "lion", hint: "The king of the jungle." },
    { word: "zebra", hint: "An animal with black and white stripes." },
    { word: "monkey", hint: "A playful animal that loves bananas." },
    { word: "elephant", hint: "The largest land animal with a trunk." },
    { word: "giraffe", hint: "The tallest animal with a long neck." },
    { word: "rabbit", hint: "A small animal that hops and loves carrots." },
    { word: "panda", hint: "A black-and-white bear that eats bamboo." },
    { word: "bear", hint: "A large animal that hibernates in winter." },
    { word: "koala", hint: "An Australian animal that loves eucalyptus leaves." },
    { word: "ocean", hint: "A vast body of salt water covering most of Earth." },
    { word: "river", hint: "A flowing body of water leading to the sea." },
    { word: "lake", hint: "A large body of water surrounded by land." },
    { word: "cloud", hint: "A fluffy white shape in the sky." },
    { word: "rain", hint: "Water that falls from clouds." },
    { word: "snow", hint: "White, fluffy flakes that fall in winter." },
    { word: "storm", hint: "Weather with strong winds, rain, or thunder." },
    { word: "breeze", hint: "A gentle wind." },
    { word: "sun", hint: "The star that gives us light and heat." },
    { word: "star", hint: "A glowing object in the night sky." },
    { word: "pizza", hint: "A dish with cheese, sauce, and toppings on dough." },
    { word: "pasta", hint: "A popular Italian dish made from noodles." },
    { word: "burger", hint: "A sandwich with a beef patty inside." },
    { word: "salad", hint: "A healthy dish made with vegetables." },
    { word: "cheese", hint: "A dairy product often yellow or white." },
    { word: "bread", hint: "A staple food used to make sandwiches." },
    { word: "candy", hint: "A sweet treat made with sugar." },
    { word: "cookie", hint: "A baked treat often with chocolate chips." },
    { word: "cake", hint: "A dessert often served at birthdays." },
    { word: "donut", hint: "A sweet, fried treat with a hole in the center." },
    { word: "chair", hint: "A piece of furniture to sit on." },
    { word: "table", hint: "A piece of furniture with a flat surface." },
    { word: "pillow", hint: "A cushion for resting your head while sleeping." },
    { word: "window", hint: "An opening in a wall that lets in light." },
    { word: "floor", hint: "The surface you walk on inside a building." },
    { word: "door", hint: "An entryway to a room or building." },
    { word: "lamp", hint: "A device used to produce light." },
    { word: "clock", hint: "A device that shows the time." },
    { word: "balloon", hint: "A colorful object filled with air or helium." },
    { word: "kite", hint: "A toy that flies in the wind." },
    { word: "puzzle", hint: "A game that challenges you to solve it." },
     { word: "dog", hint: "A loyal pet that barks." },
    { word: "cat", hint: "A small pet that purrs." },
    { word: "bird", hint: "An animal that can fly." },
    { word: "cow", hint: "An animal that gives us milk." },
    { word: "pig", hint: "A farm animal that says 'oink.'" },
    { word: "duck", hint: "A bird that quacks and loves water." },
    { word: "frog", hint: "A green animal that hops and lives near water." },
    { word: "fish", hint: "An animal that swims in water." },
    { word: "bee", hint: "An insect that makes honey." },
    { word: "ant", hint: "A small insect that works in groups." },
    { word: "car", hint: "A vehicle with four wheels." },
    { word: "bus", hint: "A large vehicle that carries people." },
    { word: "bike", hint: "A two-wheeled vehicle you pedal." },
    { word: "train", hint: "A vehicle that runs on tracks." },
    { word: "ship", hint: "A large boat that sails on the sea." },
    { word: "plane", hint: "A vehicle that flies in the air." },
    { word: "shoe", hint: "Something you wear on your feet." },
    { word: "hat", hint: "Something you wear on your head." },
    { word: "coat", hint: "A warm piece of clothing for winter." },
    { word: "sock", hint: "Clothing you wear on your feet under shoes." },
    { word: "shirt", hint: "Clothing you wear on your upper body." },
    { word: "pants", hint: "Clothing you wear on your legs." },
    { word: "sun", hint: "The star that gives us light and heat." },
    { word: "moon", hint: "The object that shines at night in the sky." },
    { word: "star", hint: "A glowing object in the night sky." },
    { word: "tree", hint: "A tall plant with leaves and a trunk." },
    { word: "grass", hint: "The green plants that cover the ground." },
    { word: "flower", hint: "A colorful plant that blooms." },
    { word: "rock", hint: "A solid piece of the Earth." },
    { word: "sand", hint: "Small grains found on beaches." },
    { word: "cloud", hint: "A fluffy white shape in the sky." },
    { word: "rain", hint: "Water that falls from clouds." },
    { word: "snow", hint: "White, fluffy flakes that fall in winter." },
    { word: "wind", hint: "Air that moves around us." },
    { word: "ice", hint: "Frozen water." },
    { word: "fire", hint: "Hot and bright flames." },
    { word: "book", hint: "Something you read with pages." },
    { word: "pen", hint: "A tool used for writing." },
    { word: "desk", hint: "A table used for studying or working." },
    { word: "bag", hint: "Something you carry things in." },
    { word: "clock", hint: "A device that tells the time." },
    { word: "bell", hint: "A metal object that rings." },
    { word: "box", hint: "A container with flat sides." },
    { word: "toy", hint: "Something kids play with." },
    { word: "ball", hint: "A round object used in games." },
    { word: "cake", hint: "A dessert often served at birthdays." },
    { word: "milk", hint: "A white drink from cows." },
    { word: "egg", hint: "A food with a shell laid by hens." },
    { word: "corn", hint: "A yellow vegetable on a cob." }  
  ];
  
